keep_prev_scale: false

shape_color: auto   # null, 'auto', 'manual'
shift_auto_shape_color: 0
label_colors: null

# canvas
epsilon: 10.0

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [D, Ctrl+Shift+D]
  open_prev: [A, Ctrl+Shift+A]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  hide_all: Ctrl+X
  show_all: Ctrl+C
  toggle_polygon: Ctrl+V

  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  edit_polygon: Ctrl+J
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  add_point_to_edge: Ctrl+Shift+P
  edit_label: Ctrl+E
  toggle_keep_prev_mode: Ctrl+P
